// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: audio2face.proto

#include "audio2face.pb.h"

#include <algorithm>

#include <Protobuf/lotus/google/protobuf/stubs/common.h>
#include <Protobuf/lotus/google/protobuf/stubs/port.h>
#include <Protobuf/lotus/google/protobuf/stubs/once.h>
#include <Protobuf/lotus/google/protobuf/io/coded_stream.h>
#include <Protobuf/lotus/google/protobuf/wire_format_lite_inl.h>
#include <Protobuf/lotus/google/protobuf/descriptor.h>
#include <Protobuf/lotus/google/protobuf/generated_message_reflection.h>
#include <Protobuf/lotus/google/protobuf/reflection_ops.h>
#include <Protobuf/lotus/google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)
namespace tutorial {
class RequestDefaultTypeInternal {
 public:
  ::lotus::google::protobuf::internal::ExplicitlyConstructed<Request>
      _instance;
} _Request_default_instance_;
class ResponseDefaultTypeInternal {
 public:
  ::lotus::google::protobuf::internal::ExplicitlyConstructed<Response>
      _instance;
} _Response_default_instance_;
}  // namespace tutorial
namespace protobuf_audio2face_2eproto {
void InitDefaultsRequestImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::lotus::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::lotus::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tutorial::_Request_default_instance_;
    new (ptr) ::tutorial::Request();
    ::lotus::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tutorial::Request::InitAsDefaultInstance();
}

void InitDefaultsRequest() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::lotus::google::protobuf::GoogleOnceInit(&once, &InitDefaultsRequestImpl);
}

void InitDefaultsResponseImpl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  ::lotus::google::protobuf::internal::InitProtobufDefaultsForceUnique();
#else
  ::lotus::google::protobuf::internal::InitProtobufDefaults();
#endif  // GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
  {
    void* ptr = &::tutorial::_Response_default_instance_;
    new (ptr) ::tutorial::Response();
    ::lotus::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::tutorial::Response::InitAsDefaultInstance();
}

void InitDefaultsResponse() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::lotus::google::protobuf::GoogleOnceInit(&once, &InitDefaultsResponseImpl);
}

::lotus::google::protobuf::Metadata file_level_metadata[2];

const ::lotus::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::Request, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::Request, content_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::Request, tts_type_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::Response, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::Response, content_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::Response, emotion_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::Response, bs_value_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::Response, bs_key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::tutorial::Response, wav_data_),
};
static const ::lotus::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::tutorial::Request)},
  { 7, -1, sizeof(::tutorial::Response)},
};

static ::lotus::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::lotus::google::protobuf::Message*>(&::tutorial::_Request_default_instance_),
  reinterpret_cast<const ::lotus::google::protobuf::Message*>(&::tutorial::_Response_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  ::lotus::google::protobuf::MessageFactory* factory = NULL;
  AssignDescriptors(
      "audio2face.proto", schemas, file_default_instances, TableStruct::offsets, factory,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::lotus::google::protobuf::GoogleOnceInit(&once, &protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::lotus::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\020audio2face.proto\022\010tutorial\",\n\007Request\022"
      "\017\n\007content\030\001 \001(\t\022\020\n\010tts_type\030\002 \001(\t\"`\n\010Re"
      "sponse\022\017\n\007content\030\001 \001(\t\022\017\n\007emotion\030\002 \001(\002"
      "\022\020\n\010bs_value\030\003 \003(\002\022\016\n\006bs_key\030\004 \003(\t\022\020\n\010wa"
      "v_data\030\005 \001(\014b\006proto3"
  };
  ::lotus::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 180);
  ::lotus::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "audio2face.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static GOOGLE_PROTOBUF_DECLARE_ONCE(once);
  ::lotus::google::protobuf::GoogleOnceInit(&once, &AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_audio2face_2eproto
namespace tutorial {

// ===================================================================

void Request::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Request::kContentFieldNumber;
const int Request::kTtsTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Request::Request()
  : ::lotus::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_audio2face_2eproto::InitDefaultsRequest();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tutorial.Request)
}
Request::Request(const Request& from)
  : ::lotus::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  content_.UnsafeSetDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.content().size() > 0) {
    content_.AssignWithDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  tts_type_.UnsafeSetDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.tts_type().size() > 0) {
    tts_type_.AssignWithDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tts_type_);
  }
  // @@protoc_insertion_point(copy_constructor:tutorial.Request)
}

void Request::SharedCtor() {
  content_.UnsafeSetDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tts_type_.UnsafeSetDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _cached_size_ = 0;
}

Request::~Request() {
  // @@protoc_insertion_point(destructor:tutorial.Request)
  SharedDtor();
}

void Request::SharedDtor() {
  content_.DestroyNoArena(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tts_type_.DestroyNoArena(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Request::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::lotus::google::protobuf::Descriptor* Request::descriptor() {
  ::protobuf_audio2face_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_audio2face_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Request& Request::default_instance() {
  ::protobuf_audio2face_2eproto::InitDefaultsRequest();
  return *internal_default_instance();
}

Request* Request::New(::lotus::google::protobuf::Arena* arena) const {
  Request* n = new Request;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Request::Clear() {
// @@protoc_insertion_point(message_clear_start:tutorial.Request)
  ::lotus::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  content_.ClearToEmptyNoArena(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  tts_type_.ClearToEmptyNoArena(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool Request::MergePartialFromCodedStream(
    ::lotus::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::lotus::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tutorial.Request)
  for (;;) {
    ::std::pair< ::lotus::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::lotus::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string content = 1;
      case 1: {
        if (static_cast< ::lotus::google::protobuf::uint8>(tag) ==
            static_cast< ::lotus::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::lotus::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          DO_(::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content().data(), static_cast<int>(this->content().length()),
            ::lotus::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.Request.content"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string tts_type = 2;
      case 2: {
        if (static_cast< ::lotus::google::protobuf::uint8>(tag) ==
            static_cast< ::lotus::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::lotus::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_tts_type()));
          DO_(::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->tts_type().data(), static_cast<int>(this->tts_type().length()),
            ::lotus::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.Request.tts_type"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::lotus::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tutorial.Request)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tutorial.Request)
  return false;
#undef DO_
}

void Request::SerializeWithCachedSizes(
    ::lotus::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tutorial.Request)
  ::lotus::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (this->content().size() > 0) {
    ::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::lotus::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.Request.content");
    ::lotus::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->content(), output);
  }

  // string tts_type = 2;
  if (this->tts_type().size() > 0) {
    ::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tts_type().data(), static_cast<int>(this->tts_type().length()),
      ::lotus::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.Request.tts_type");
    ::lotus::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->tts_type(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::lotus::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tutorial.Request)
}

::lotus::google::protobuf::uint8* Request::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::lotus::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tutorial.Request)
  ::lotus::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (this->content().size() > 0) {
    ::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::lotus::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.Request.content");
    target =
      ::lotus::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->content(), target);
  }

  // string tts_type = 2;
  if (this->tts_type().size() > 0) {
    ::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->tts_type().data(), static_cast<int>(this->tts_type().length()),
      ::lotus::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.Request.tts_type");
    target =
      ::lotus::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->tts_type(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::lotus::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tutorial.Request)
  return target;
}

size_t Request::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tutorial.Request)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::lotus::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string content = 1;
  if (this->content().size() > 0) {
    total_size += 1 +
      ::lotus::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  // string tts_type = 2;
  if (this->tts_type().size() > 0) {
    total_size += 1 +
      ::lotus::google::protobuf::internal::WireFormatLite::StringSize(
        this->tts_type());
  }

  int cached_size = ::lotus::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Request::MergeFrom(const ::lotus::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tutorial.Request)
  GOOGLE_DCHECK_NE(&from, this);
  const Request* source =
      ::lotus::google::protobuf::internal::DynamicCastToGenerated<const Request>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tutorial.Request)
    ::lotus::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tutorial.Request)
    MergeFrom(*source);
  }
}

void Request::MergeFrom(const Request& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tutorial.Request)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::lotus::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.content().size() > 0) {

    content_.AssignWithDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  if (from.tts_type().size() > 0) {

    tts_type_.AssignWithDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.tts_type_);
  }
}

void Request::CopyFrom(const ::lotus::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tutorial.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Request::CopyFrom(const Request& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tutorial.Request)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Request::IsInitialized() const {
  return true;
}

void Request::Swap(Request* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Request::InternalSwap(Request* other) {
  using std::swap;
  content_.Swap(&other->content_);
  tts_type_.Swap(&other->tts_type_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::lotus::google::protobuf::Metadata Request::GetMetadata() const {
  protobuf_audio2face_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_audio2face_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Response::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Response::kContentFieldNumber;
const int Response::kEmotionFieldNumber;
const int Response::kBsValueFieldNumber;
const int Response::kBsKeyFieldNumber;
const int Response::kWavDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Response::Response()
  : ::lotus::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (GOOGLE_PREDICT_TRUE(this != internal_default_instance())) {
    ::protobuf_audio2face_2eproto::InitDefaultsResponse();
  }
  SharedCtor();
  // @@protoc_insertion_point(constructor:tutorial.Response)
}
Response::Response(const Response& from)
  : ::lotus::google::protobuf::Message(),
      _internal_metadata_(NULL),
      bs_value_(from.bs_value_),
      bs_key_(from.bs_key_),
      _cached_size_(0) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  content_.UnsafeSetDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.content().size() > 0) {
    content_.AssignWithDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  wav_data_.UnsafeSetDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.wav_data().size() > 0) {
    wav_data_.AssignWithDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.wav_data_);
  }
  emotion_ = from.emotion_;
  // @@protoc_insertion_point(copy_constructor:tutorial.Response)
}

void Response::SharedCtor() {
  content_.UnsafeSetDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  wav_data_.UnsafeSetDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  emotion_ = 0;
  _cached_size_ = 0;
}

Response::~Response() {
  // @@protoc_insertion_point(destructor:tutorial.Response)
  SharedDtor();
}

void Response::SharedDtor() {
  content_.DestroyNoArena(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  wav_data_.DestroyNoArena(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Response::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::lotus::google::protobuf::Descriptor* Response::descriptor() {
  ::protobuf_audio2face_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_audio2face_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Response& Response::default_instance() {
  ::protobuf_audio2face_2eproto::InitDefaultsResponse();
  return *internal_default_instance();
}

Response* Response::New(::lotus::google::protobuf::Arena* arena) const {
  Response* n = new Response;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Response::Clear() {
// @@protoc_insertion_point(message_clear_start:tutorial.Response)
  ::lotus::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  bs_value_.Clear();
  bs_key_.Clear();
  content_.ClearToEmptyNoArena(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  wav_data_.ClearToEmptyNoArena(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited());
  emotion_ = 0;
  _internal_metadata_.Clear();
}

bool Response::MergePartialFromCodedStream(
    ::lotus::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::lotus::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tutorial.Response)
  for (;;) {
    ::std::pair< ::lotus::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::lotus::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string content = 1;
      case 1: {
        if (static_cast< ::lotus::google::protobuf::uint8>(tag) ==
            static_cast< ::lotus::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::lotus::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          DO_(::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content().data(), static_cast<int>(this->content().length()),
            ::lotus::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.Response.content"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float emotion = 2;
      case 2: {
        if (static_cast< ::lotus::google::protobuf::uint8>(tag) ==
            static_cast< ::lotus::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::lotus::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::lotus::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &emotion_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated float bs_value = 3;
      case 3: {
        if (static_cast< ::lotus::google::protobuf::uint8>(tag) ==
            static_cast< ::lotus::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_((::lotus::google::protobuf::internal::WireFormatLite::ReadPackedPrimitive<
                   float, ::lotus::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, this->mutable_bs_value())));
        } else if (
            static_cast< ::lotus::google::protobuf::uint8>(tag) ==
            static_cast< ::lotus::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {
          DO_((::lotus::google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitiveNoInline<
                   float, ::lotus::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 1, 26u, input, this->mutable_bs_value())));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string bs_key = 4;
      case 4: {
        if (static_cast< ::lotus::google::protobuf::uint8>(tag) ==
            static_cast< ::lotus::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::lotus::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_bs_key()));
          DO_(::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->bs_key(this->bs_key_size() - 1).data(),
            static_cast<int>(this->bs_key(this->bs_key_size() - 1).length()),
            ::lotus::google::protobuf::internal::WireFormatLite::PARSE,
            "tutorial.Response.bs_key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bytes wav_data = 5;
      case 5: {
        if (static_cast< ::lotus::google::protobuf::uint8>(tag) ==
            static_cast< ::lotus::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::lotus::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_wav_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::lotus::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tutorial.Response)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tutorial.Response)
  return false;
#undef DO_
}

void Response::SerializeWithCachedSizes(
    ::lotus::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tutorial.Response)
  ::lotus::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (this->content().size() > 0) {
    ::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::lotus::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.Response.content");
    ::lotus::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->content(), output);
  }

  // float emotion = 2;
  if (this->emotion() != 0) {
    ::lotus::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->emotion(), output);
  }

  // repeated float bs_value = 3;
  if (this->bs_value_size() > 0) {
    ::lotus::google::protobuf::internal::WireFormatLite::WriteTag(3, ::lotus::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED, output);
    output->WriteVarint32(static_cast< ::lotus::google::protobuf::uint32>(
        _bs_value_cached_byte_size_));
    ::lotus::google::protobuf::internal::WireFormatLite::WriteFloatArray(
      this->bs_value().data(), this->bs_value_size(), output);
  }

  // repeated string bs_key = 4;
  for (int i = 0, n = this->bs_key_size(); i < n; i++) {
    ::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bs_key(i).data(), static_cast<int>(this->bs_key(i).length()),
      ::lotus::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.Response.bs_key");
    ::lotus::google::protobuf::internal::WireFormatLite::WriteString(
      4, this->bs_key(i), output);
  }

  // bytes wav_data = 5;
  if (this->wav_data().size() > 0) {
    ::lotus::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      5, this->wav_data(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::lotus::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:tutorial.Response)
}

::lotus::google::protobuf::uint8* Response::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::lotus::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tutorial.Response)
  ::lotus::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content = 1;
  if (this->content().size() > 0) {
    ::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::lotus::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.Response.content");
    target =
      ::lotus::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->content(), target);
  }

  // float emotion = 2;
  if (this->emotion() != 0) {
    target = ::lotus::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->emotion(), target);
  }

  // repeated float bs_value = 3;
  if (this->bs_value_size() > 0) {
    target = ::lotus::google::protobuf::internal::WireFormatLite::WriteTagToArray(
      3,
      ::lotus::google::protobuf::internal::WireFormatLite::WIRETYPE_LENGTH_DELIMITED,
      target);
    target = ::lotus::google::protobuf::io::CodedOutputStream::WriteVarint32ToArray(
        static_cast< ::lotus::google::protobuf::int32>(
            _bs_value_cached_byte_size_), target);
    target = ::lotus::google::protobuf::internal::WireFormatLite::
      WriteFloatNoTagToArray(this->bs_value_, target);
  }

  // repeated string bs_key = 4;
  for (int i = 0, n = this->bs_key_size(); i < n; i++) {
    ::lotus::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->bs_key(i).data(), static_cast<int>(this->bs_key(i).length()),
      ::lotus::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "tutorial.Response.bs_key");
    target = ::lotus::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(4, this->bs_key(i), target);
  }

  // bytes wav_data = 5;
  if (this->wav_data().size() > 0) {
    target =
      ::lotus::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        5, this->wav_data(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::lotus::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:tutorial.Response)
  return target;
}

size_t Response::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tutorial.Response)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::lotus::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::lotus::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated float bs_value = 3;
  {
    unsigned int count = static_cast<unsigned int>(this->bs_value_size());
    size_t data_size = 4UL * count;
    if (data_size > 0) {
      total_size += 1 +
        ::lotus::google::protobuf::internal::WireFormatLite::Int32Size(
            static_cast< ::lotus::google::protobuf::int32>(data_size));
    }
    int cached_size = ::lotus::google::protobuf::internal::ToCachedSize(data_size);
    GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
    _bs_value_cached_byte_size_ = cached_size;
    GOOGLE_SAFE_CONCURRENT_WRITES_END();
    total_size += data_size;
  }

  // repeated string bs_key = 4;
  total_size += 1 *
      ::lotus::google::protobuf::internal::FromIntSize(this->bs_key_size());
  for (int i = 0, n = this->bs_key_size(); i < n; i++) {
    total_size += ::lotus::google::protobuf::internal::WireFormatLite::StringSize(
      this->bs_key(i));
  }

  // string content = 1;
  if (this->content().size() > 0) {
    total_size += 1 +
      ::lotus::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  // bytes wav_data = 5;
  if (this->wav_data().size() > 0) {
    total_size += 1 +
      ::lotus::google::protobuf::internal::WireFormatLite::BytesSize(
        this->wav_data());
  }

  // float emotion = 2;
  if (this->emotion() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::lotus::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Response::MergeFrom(const ::lotus::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tutorial.Response)
  GOOGLE_DCHECK_NE(&from, this);
  const Response* source =
      ::lotus::google::protobuf::internal::DynamicCastToGenerated<const Response>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tutorial.Response)
    ::lotus::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tutorial.Response)
    MergeFrom(*source);
  }
}

void Response::MergeFrom(const Response& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tutorial.Response)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::lotus::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  bs_value_.MergeFrom(from.bs_value_);
  bs_key_.MergeFrom(from.bs_key_);
  if (from.content().size() > 0) {

    content_.AssignWithDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  if (from.wav_data().size() > 0) {

    wav_data_.AssignWithDefault(&::lotus::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.wav_data_);
  }
  if (from.emotion() != 0) {
    set_emotion(from.emotion());
  }
}

void Response::CopyFrom(const ::lotus::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tutorial.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Response::CopyFrom(const Response& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tutorial.Response)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Response::IsInitialized() const {
  return true;
}

void Response::Swap(Response* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Response::InternalSwap(Response* other) {
  using std::swap;
  bs_value_.InternalSwap(&other->bs_value_);
  bs_key_.InternalSwap(&other->bs_key_);
  content_.Swap(&other->content_);
  wav_data_.Swap(&other->wav_data_);
  swap(emotion_, other->emotion_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  swap(_cached_size_, other->_cached_size_);
}

::lotus::google::protobuf::Metadata Response::GetMetadata() const {
  protobuf_audio2face_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_audio2face_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace tutorial

// @@protoc_insertion_point(global_scope)
